src/Component/Order/Entity/OrderInterface.php
<?php

/*
 * This file has been created by developers from BitBag.
 * Feel free to contact us once you face any issues or want to start
 * You can find more information about us on https://bitbag.io and write us
 * an email on hello@bitbag.io.
 */

declare(strict_types=1);

namespace BitBag\OpenMarketplace\Component\Order\Entity;

use BitBag\OpenMarketplace\Component\Vendor\Entity\VendorInterface;
use BitBag\OpenMarketplace\Component\Vendor\OptionalVendorAwareInterface;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Core\Model\OrderInterface as BaseOrderInterface;

interface OrderInterface extends BaseOrderInterface, OptionalVendorAwareInterface
{
    public const PRIMARY_ORDER_MODE = 'primary';

    public const SECONDARY_ORDER_MODE = 'secondary';

    public function getPrimaryOrder(): ?self;

    public function setPrimaryOrder(?self $primaryOrder): void;

    public function addSecondaryOrder(self $secondaryOrder): void;

    /** @return Collection<int, OrderInterface> */
    public function getSecondaryOrders(): Collection;

    public function hasVendorShipment(?VendorInterface $vendor): bool;

    public function getVendorsFromOrderItems(): array;

    public function getShipmentByVendor(?VendorInterface $vendor): ?ShipmentInterface;

    public function getShipmentWithoutVendor(): ?ShipmentInterface;

    public function hasShippableItemsWithVendor(?VendorInterface $vendor): bool;

    public function getMode(): string;

    public function setMode(string $mode): void;

    public function isPrimary(): bool;

    public function getCommissionTotal(): int;

    public function setCommissionTotal(int $commissionTotal): void;

    public function getPaidAt(): ?\DateTimeInterface;

    public function setPaidAt(?\DateTimeInterface $paidAt): void;

    public function getTotalProfitAmount(): int;
}

src/Component/Order/Entity/OrderItemTrait.php
<?php

/*
 * This file was created by developers working at BitBag
 * Do you need more information about us and what we do? Visit our https://bitbag.io website!
 * We are hiring developers from all over the world. Join us and start your new, exciting adventure and become part of us: https://bitbag.io/career
*/

declare(strict_types=1);

namespace BitBag\OpenMarketplace\Component\Order\Entity;

use BitBag\OpenMarketplace\Component\Product\Entity\ProductInterface;
use BitBag\OpenMarketplace\Component\Vendor\Entity\VendorInterface;

trait OrderItemTrait
{
    public function getProductOwner(): ?VendorInterface
    {
        /** @var ProductInterface $product */
        $product = $this->getProduct();
        /** @var VendorInterface $vendor */
        $vendor = $product->getVendor();

        return $vendor;
    }
}

templates/Context/Shop/Checkout/ThankYouPage/Table/_headers.html.twig
<tr>
    <th>{{ 'open_marketplace.ui.vendors'|trans }}</th>
    <th>{{ 'sylius.ui.item'|trans }}</th>
    <th>{{ 'sylius.ui.shipment'|trans }}</th>
</tr>

templates/Context/Shop/Checkout/ThankYouPage/Table/_item.html.twig
<tr>
    <td class="center aligned">
        {% if secondaryOrder.vendor.companyName is defined %}
            {{ secondaryOrder.vendor.companyName }}
        {% endif %}
    </td>
    <td>
        {% for item in secondaryOrder.items %}
            {% if secondaryOrder.items|length > 1 %}
                {% if loop.last %}
                    {% include '@SyliusShop/Product/_info.html.twig' with {'variant': item.variant} %}
                {% else %}
                    {% include '@SyliusShop/Product/_info.html.twig' with {'variant': item.variant} %}
                    <div class="ui divider"></div>
                {% endif %}
            {% else %}
                {% include '@SyliusShop/Product/_info.html.twig' with {'variant': item.variant} %}
            {% endif %}
        {% endfor %}
    </td>
    <td class="center aligned">{% include 'Context/Shop/Checkout/ThankYouPage/Table/_shipments.html.twig' %}</td>
</tr>

templates/Context/Shop/Checkout/ThankYouPage/Table/_items.html.twig
{% for secondaryOrder in order.secondaryOrders %}
    {% include 'Context/Shop/Checkout/ThankYouPage/Table/_item.html.twig' %}
{% endfor %}

templates/Context/Shop/Checkout/ThankYouPage/Table/_shipments.html.twig
{% set item = secondaryOrder.items|last  %}
{% for shipment in order.shipments %}
    {% if shipment.vendor is same as item.productOwner %}
    {% set state = shipment.state %}
    <div class="ui small icon message">
        <i class="truck icon"></i>
        <div class="content">
            <div class="header">
                {{ shipment.method }}
            </div>
        </div>
    </div>
    {% endif %}
{% endfor %}